# Generated by Django 5.2.3 on 2025-07-21 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_updated',
        ),
        migrations.AlterField(
            model_name='master',
            name='services',
            field=models.ManyToManyField(related_name='provided_by', to='core.service', verbose_name='Услуги'),
        ),
        migrations.AlterField(
            model_name='order',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.master', verbose_name='Мастер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('confirmed', 'Подтвержденная'), ('completed', 'Выполненная'), ('canceled', 'Отменена')], default='new', max_length=50, verbose_name='Статус'),
        ),
    ]
