# Generated by Django 5.2.3 on 2025-08-01 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_master_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('ai_moderated', 'На модерации'), ('ai_approved', 'Одобрен AI'), ('ai_rejected', 'Отклонен AI'), ('published', 'Опубликован'), ('archived', 'В архиве')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='review',
            name='client_name',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='review',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='core.master', verbose_name='Мастер'),
        ),
        migrations.AlterField(
            model_name='review',
            name='photo',
            field=models.ImageField(null=True, upload_to='reviews/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, 'Ужасно'), (2, 'Плохо'), (3, 'Нормально'), (4, 'Хорошо'), (5, 'Отлично')], default=5, verbose_name='Рейтинг'),
        ),
    ]
