# Generated by Django 5.2.3 on 2025-08-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_review_status_alter_review_client_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/', verbose_name='Фотография'),
        ),
    ]
