# Generated by Django 5.2.3 on 2025-08-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_review_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликован'),
        ),
    ]
